Feat/events
she-code-africa/WOSCA-WEBSITE-BE pull request #20
Opened 2021-08-26 10:36 UTC by kengneruphine

Routes here are:
- Get all events /api/v1/events
- Post an event /api/v1/events
- Get a single event /api/v1/events/id
- update an event /api/v1/events/id
-  delete an event /api/v1/events/id

Details needed to create an event are:
- Name,
- location, 
- startTime, 
- endTime
-  description

2021-08-26 10:39 UTC, OdunayoOkebunmi commented
@kengneruphine, please can you resolve the merge conflicts?

2021-08-27 09:46 UTC, OdunayoOkebunmi requested changes

2021-08-27 09:46 UTC, OdunayoOkebunmi commented on src/server/controllers/event/event.controller.js
> +      return errorResponse(res, req, 409, { message: 'An event with this name already exist' });
@kengneruphine should the name of the event be unique?

2021-08-27 09:46 UTC, OdunayoOkebunmi commented on src/server/server.js
> +    router.get('/', (req, res) => res.status(200).send({ message: 'Welcome to WOSCA site API' }));
Is there a reason why you changed it from `app` to `router`?

2021-08-27 09:56 UTC, kengneruphine commented on src/server/server.js
> +    router.get('/', (req, res) => res.status(200).send({ message: 'Welcome to WOSCA site API' }));
Is because I changed the location of the /api/v1 to the server.js file
and also I am exporting router from the index.js file from the routes folder

2021-08-27 09:58 UTC, kengneruphine commented on src/server/controllers/event/event.controller.js
> +      return errorResponse(res, req, 409, { message: 'An event with this name already exist' });
Was looking for a unique identifier for an event apart of the id. So I thought of the name

2021-08-27 10:01 UTC, kengneruphine commented on src/server/server.js
> +    router.get('/', (req, res) => res.status(200).send({ message: 'Welcome to WOSCA site API' }));
And I think is more understandable like this

2021-08-27 10:12 UTC, OdunayoOkebunmi commented on src/server/controllers/event/event.controller.js
> +      return errorResponse(res, req, 409, { message: 'An event with this name already exist' });
Can we add a slug instead?

2021-08-27 10:13 UTC, kengneruphine commented on src/server/controllers/event/event.controller.js
> +      return errorResponse(res, req, 409, { message: 'An event with this name already exist' });
Yeah

2021-08-27 10:13 UTC, kengneruphine commented on src/server/controllers/event/event.controller.js
> +      return errorResponse(res, req, 409, { message: 'An event with this name already exist' });
that will be entered by the user?

2021-09-01 11:45 UTC, OdunayoOkebunmi commented
@kengneruphine, I have updated the code

2021-09-10 08:31 UTC, OdunayoOkebunmi approved these changes

2021-09-10 08:31 UTC, merged